### ISSUE TITLE
Create a demo page that shows the library functionality

### ISSUE THREAD

**Issue by kpuputti** [kpuputti/JSONCache#1]
The motivation for the demo page is to show the functionality and the benefits of the library especially with a slow or flaky network connection.

The demo page should have at least the following functionality:
- A configuration form in which the user can change the JSONCache settings (e.g. waitTime, numTries, or itemLifetime)
- A toggle switch for online/offline mode (offline can e.g. be achieved by mocking the jQuery.ajax function to always call the error error function)
- Some list of different JSON files that can be downloaded (preferably at least some big data to show longer download times)
- Some visualization of the fetched data
- Mobile browser support for testing
- PhoneGap etc. support for wrapping the app to a native package for testing
- Randomized failing in network fetching?

**Comment by jareware** [comment]
See https://github.com/kpuputti/JSONCache/pull/5 for a related pull request.

**Comment by jareware** [comment]
Oh, github is NOT strong in this one.

Closing as duplicate in favor of #5.

**Comment by jareware** [comment]
Never mind; see #5 for the related pull request.

**Comment by kpuputti** [comment]
I'll try to make a Phonegap app of the demo for testing.

**Comment by kpuputti** [comment]
> I'll try to make a Phonegap app of the demo for testing.

Or maybe I won't!
