### ISSUE TITLE
Keep track of current cache size and clean items when it begins to be full

### ISSUE THREAD

**Issue by kpuputti** [kpuputti/JSONCache#2]
Characters can be expected to be 16 bits each and max size of 2.5Mb for the whole localStorage cache.

There should be a configurable setting for the max cache size, and some automated functionality to clean oldest items (see the JSONCache.purgeOldest and JSONCache.clean functions) when the cache is about to be full.

**Comment by jareware** [comment]
See https://github.com/jareware/JSONCache/tree/cache-size and https://github.com/jareware/JSONCache/tree/cache-eviction for relevant feature branches.  #5 should be merged into master before these though...
